# Generated by Django 3.2.7 on 2023-02-08 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('location', models.CharField(max_length=127, verbose_name='Локация')),
                ('image', models.ImageField(upload_to='merop/image/', verbose_name='Картинка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merops', to='company.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
