# Generated by Django 3.2.7 on 2023-02-08 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('video', models.FileField(upload_to='video/video/video/', verbose_name='Видео')),
                ('when', models.DateField(verbose_name='Когда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='company.company')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видосы',
            },
        ),
    ]
